# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rename index.html to 404.html
        run: cp index.html 404.html && rm index.html
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: ./
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
